SRCS := $(wildcard *.hpp)
CFLAGS := -Wall -Werror -O3 -std=c++11
CC := g++

.PHONY: clean

all: loader

loader: loader.cpp $(SRCS)
    @echo "Building $@..."
    $(CC) -o $@ $(CFLAGS) $< `pkg-config opencv --cflags --libs`
